server:
  port: 8080

spring:
  datasource:
    maria:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/common_test
      username: userTest
      password: password
