server:
  prot: 8181

spring:
  datasource:
    maria:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/common_dev
      username: devUser
      password: password